const ERROR_CODE = {
    SUCCESS: 0,
    INVALID_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    NOT_ACCEPTABLE: 406,
    GONE: 410,
    UNPROCESABLE_ENTITY: 422,
    INTERNAL_SERVER_ERROR: 500
}

module.exports = ERROR_CODE
